title: Loose Ends, Long Goodbyes
description: Pop-punk from Challis, Idaho
theme: minima
plugins:
  - jekyll-sitemap
header_pages:
  - about.md
  - blog.md
  - music.md
  - contact.md
url: "https://looseendslonggoodbyes.com"
baseurl: ""