title: Loose Ends, Long Goodbyes
description: Pop-punk demos and updates.
theme: minima
plugins:
  - jekyll-sitemap
header_pages:
  - about.md
  - blog.md
  - music.md
  - contact.md
url: "https://looseendslonggoodbyes.com"